// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4iA-mc3HWJGAgGI1FMFsWIZyEM0YV-xE',
    appId: '1:46150611821:web:1483c5473d8f30e3f5a064',
    messagingSenderId: '46150611821',
    projectId: 'onlinejobportal-46987',
    authDomain: 'onlinejobportal-46987.firebaseapp.com',
    storageBucket: 'onlinejobportal-46987.appspot.com',
    measurementId: 'G-VM5CLYLQJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Iy7-6ImmSYOphYhYJGLd8VcG0V8OKJU',
    appId: '1:46150611821:android:0eea6284719eace4f5a064',
    messagingSenderId: '46150611821',
    projectId: 'onlinejobportal-46987',
    storageBucket: 'onlinejobportal-46987.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmg-PxfK_lFxFARsC3TanWrvnDiLlMBIo',
    appId: '1:46150611821:ios:0b5abaa7924ead8cf5a064',
    messagingSenderId: '46150611821',
    projectId: 'onlinejobportal-46987',
    storageBucket: 'onlinejobportal-46987.appspot.com',
    androidClientId: '46150611821-923on83b992m6jnoenmft4nprfibp8t2.apps.googleusercontent.com',
    iosClientId: '46150611821-hgs5b6vibfgu269dj7oe0pnlhfbjn80e.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineJobPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmg-PxfK_lFxFARsC3TanWrvnDiLlMBIo',
    appId: '1:46150611821:ios:0b5abaa7924ead8cf5a064',
    messagingSenderId: '46150611821',
    projectId: 'onlinejobportal-46987',
    storageBucket: 'onlinejobportal-46987.appspot.com',
    androidClientId: '46150611821-923on83b992m6jnoenmft4nprfibp8t2.apps.googleusercontent.com',
    iosClientId: '46150611821-hgs5b6vibfgu269dj7oe0pnlhfbjn80e.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineJobPortal',
  );
}
